name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🔥 HotFixes'
    label: 'hot'
  - title: '🚀 New Features'
    label: 'enhancement'
  - title: '🛠️ Feature Changes'
    label: 'fix'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'documentation'
      - 'refactor'
      - 'test'
      - 'style'
  - title: '🤖 Dependencies'
    label: 'dependencies'
autolabeler:
  - label: 'enhancement'
    title:
      - '/feat\:.+/'
  - label: 'fix'
    title:
      - '/fix\:.+/'
  - label: 'bug'
    title:
      - '/bug\:.+/'
  - label: 'hot'
    title:
      - '/hot\:.+/'
  - label: 'refactor'
    title:
      - '/refactor\:.+/'
  - label: 'chore'
    title:
      - '/chore\:.+/'
  - label: 'documentation'
    title:
      - '/docs{0,1}\:.+/'
  - label: 'style'
    title:
      - '/style\:.+/'
  - label: 'test'
    title:
      - '/test\:.+/'
  - label: 'dependencies'
    title:
      - '/dep\:.+/'
  - label: 'work in progress'
    title:
      - '/\:wip.+/'
  - label: 'follow up'
    title:
      - '/\:fu.+/'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-labels: # develop -> main 으로 가는 PR 을 릴리즈 노트에서 표시하지 않도록
  - 'release'
  - 'wip'
  - 'work in progress'
  - 'follow up'
change-template: '- $TITLE (#$NUMBER)'
template: |
  ## Changes
  $CHANGES
