name: Release and Deploy

on:
  workflow_dispatch:  # 수동으로 워크플로우를 트리거할 수 있도록 설정

env:
  CONTAINER_CONTEXT_PATH: "docker"
  DOCKERFILE_PATH: "docker/Dockerfile"

jobs:
  check-prs:
    runs-on: ubuntu-latest
    outputs:
      is_empty: ${{ steps.tag_prs.is_empty }}
      pr_numbers: ${{ steps.tag_prs.pr_numbers }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Tag PRs as released
        id: tag_prs
        run: |
          pr_numbers_var=$(gh pr list --state closed --base aivi --json number,title,labels --jq '.[] | select(.labels | map(.name) | index("released") | not) | .number')
          if [ -n "$pr_numbers" ]; then
            echo "PRs to be tagged as released found."
            echo "is_empty=false" >> "$GITHUB_OUTPUT"
            echo "pr_numbers=$pr_numbers_var" >> "$GITHUB_OUTPUT"
          else
            echo "No PRs to tag."
            echo "is_empty=true" >> "$GITHUB_OUTPUT"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  release-drafter:
    needs: check-prs
    runs-on: ubuntu-latest
    if: needs.check-prs.outputs.is_empty == false
    outputs:
      tag: ${{ steps.version.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate version tag
        id: version
        run: |
          date_version=$(date +'%Y%m%d-%H%M%S')
          echo "tag=aivi-$date_version" >> "$GITHUB_OUTPUT"

      - name: Run release-drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-configs/create-draft-project.yml
          version: ${{ steps.version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  build-and-deploy:
    needs: release-drafter
    runs-on: ubuntu-latest
    if: needs.check-prs.outputs.is_empty == false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build release package
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build
          cache-read-only: false

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: nalsm0801/ovision-server
          tag-semver: ${{ needs.release-drafter.outputs.tag }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.CONTAINER_CONTEXT_PATH }}
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}

  tag-as-released:
    needs: [release-drafter, build-and-deploy]
    runs-on: ubuntu-latest
    if: needs.check-prs.outputs.is_empty == false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Tag PRs as released
        run: |
          pr_numbers=${{ needs.check-prs.outputs.pr_numbers }}
          for pr in $pr_numbers; do
            gh pr edit $pr --add-label "released"
          done
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
