name: Check and Create PR

on:
  pull_request:
    types: [ closed ]

jobs:
  check-label-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR was merged and has 'aivi' label and targets 'develop' branch
        id: check_pr
        run: |
          if [ "${{ github.event.pull_request.merged }}" != "true" ]; then
            echo "PR was not merged. Exiting."
            exit 0
          fi

          if [ "${{ github.event.pull_request.base.ref }}" != "develop" ]; then
            echo "PR base branch is not 'develop'. Exiting."
            exit 0
          fi

          LABELS=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
                        https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels \
                        | jq -r '.[].name')

          echo "PR labels: $LABELS"

          if [[ "$LABELS" != *"aivi"* ]]; then
            echo "PR does not have 'aivi' label. Exiting."
            exit 0
          fi

          echo "PR has 'aivi' label and targets 'develop' branch. Proceeding to create a new PR."

      - name: Create a new PR to aivi branch
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          PR_TITLE="Merge $BRANCH_NAME into aivi"
          PR_BODY="This PR was automatically created to merge $BRANCH_NAME into the aivi branch."

          # JSON body 값을 변수에 저장
          JSON_BODY=$(cat <<EOF
          {
            "title": "$PR_TITLE",
            "head": "$BRANCH_NAME",
            "base": "aivi",
            "body": "$PR_BODY"
          }
          EOF
          )

          # JSON body 값 출력
          echo "JSON Body: $JSON_BODY"

          RESPONSE=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d "$JSON_BODY")

          # PR 번호 추출
          PR_NUMBER=$(echo $RESPONSE | jq -r '.number')
          echo "Created PR Number: $PR_NUMBER"
          echo "::set-output name=pr_number::$PR_NUMBER"

      - name: Merge the new PR
        run: |
          PR_NUMBER=${{ steps.create_pr.outputs.pr_number }}
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge \
            -d '{"merge_method":"merge"}'
